export type RootStackParamList = {
  Home: undefined;
  Menu: undefined;
  Deposit: undefined;
  Onboarding: undefined;
  OnboardingV3: undefined;
  OnboardingUS: undefined;
  FlowInput: undefined;
  FlowInputV3: undefined;
  FlowInputUS: undefined;
  PinwheelMock: undefined;
  FlowBankSelection: undefined;
  FlowConfirmation: { inputValue?: string };
  FlowConfirmationV3: { inputValue?: string };
  FlowConfirmationUS: undefined;
  FlowSuccess: undefined;
  PinChallengeV3: undefined;
  FlowTracker: undefined;
  FlowTrackerV3: undefined;
};
