import type { CountryConfig } from '../types';

export const co: CountryConfig = {
  code: 'co',
  displayName: 'Colombia',
  copy: {
    welcomeTitle: 'Trae tu salario',
    welcomeDescription: 'Conecta el banco donde te consignan y traemos tu salario automáticamente cada mes.',
    connectBankTitle: 'Conectar banco',
    connectBankDescription: 'Elige la institución donde recibes tu salario.',
    connectBankCta: 'Continuar',
    inputTitle: '¿Dónde recibes tu salario actualmente?',
    inputSubtitle: '',
    inputLabel: 'Tu cuenta de nómina actual',
    inputPlaceholder: 'Ingresa el número de cuenta',
    inputCallout: 'Son los dígitos de tu cuenta actual. Búscalo en tu app bancaria o extracto.',
    inputCta: 'Continuar',
    confirmationAccountHolder: 'Name account holder',
    confirmationAccountType: 'Type of account',
    confirmationSourceBank: 'Bank payroll holder',
    confirmationSourceAccount: 'Identifier account',
    confirmationDestBank: 'Nubank',
    confirmationDestAccount: 'Identifier account',
    confirmationDetailsLabel: 'Details',
    confirmationDetails: [
      { title: 'Detail #1', subtitle: 'Description' },
      { title: 'Detail #2', subtitle: 'Description' },
      { title: 'Detail #3', subtitle: 'Description' },
    ],
    confirmationLegalText: 'Legal text',
    confirmationCta: 'Call to action',
    successTitle: 'Listo',
    successDescription: 'Cuando llegue tu salario a la otra cuenta, lo traemos automáticamente.',
  },
  bankNames: ['Bancolombia', 'Davivienda', 'BBVA', 'Banco de Bogotá', 'Otros'],
  hasExtraLegalStep: false,
};
