import type { CountryConfig } from '../types';

export const us: CountryConfig = {
  code: 'us',
  displayName: 'United States',
  copy: {
    welcomeTitle: 'Bring your paycheck',
    welcomeDescription: "Connect the bank where you get paid and we'll automatically bring your paycheck every month.",
    connectBankTitle: 'Connect bank',
    connectBankDescription: 'Choose the institution where you receive your paycheck.',
    connectBankCta: 'Continue',
    inputTitle: "Let\u2019s switch your direct deposit",
    inputSubtitle: "MoneyLion partners with Pinwheel's network of over 60k employers to switch your direct deposit.",
    inputLabel: '',
    inputPlaceholder: '',
    inputCallout: "We\u2019ll use {{third party name}} to connect to your payroll account.",
    inputCta: 'Find my employer',
    confirmationAccountHolder: 'Name account holder',
    confirmationAccountType: 'Type of account',
    confirmationSourceBank: 'Bank payroll holder',
    confirmationSourceAccount: 'Identifier account',
    confirmationDestBank: 'Nubank',
    confirmationDestAccount: 'Identifier account',
    confirmationDetailsLabel: 'Details',
    confirmationDetails: [
      { title: 'Detail #1', subtitle: 'Description' },
      { title: 'Detail #2', subtitle: 'Description' },
      { title: 'Detail #3', subtitle: 'Description' },
    ],
    confirmationLegalText: 'Legal text',
    confirmationCta: 'Call to action',
    successTitle: "You're all set",
    successDescription: "When your paycheck hits the other account, we'll bring it automatically.",
  },
  bankNames: ['Chase', 'Bank of America', 'Wells Fargo', 'Citi', 'Capital One', 'Other'],
  usesThirdPartyIntegration: true,
  hasExtraLegalStep: false,
};
